feature_launchpad:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /data/warehouse.duckdb
      threads: 4
      
    prod:
      type: duckdb
      path: /data/warehouse_prod.duckdb
      threads: 8
